project_id = "bficxnetrsuyzygutztn"

[functions.extract-news-results]
verify_jwt = false

[functions.google-alerts-query]
verify_jwt = false

[functions.fetch-news-content]
verify_jwt = false

[functions.analyze-news]
verify_jwt = false

[functions.generate-teleprompter-script]
verify_jwt = false

[functions.generate-news-search-terms]
verify_jwt = false

[functions.google-news-rss]
verify_jwt = false
